type Notification {
    userName: String!
    notice: [FloorPrice]!
}

type FloorPrice @embedded {
    collection: String!
    price: String!
    direction: String!
}
type Query {
    allNotifications: [Notification!]
}