type Notification {
    userName: String!
    notice: [FloorPrice]!
}

type FloorPrice @embedded {
    collection: String!
    price: String!
    direction: String!
    chain: String!
}
type Query {
    allNotifications: [Notification!]
    notificationsByUser(userName: String!): [Notification!]
}
